const request = require('supertest');

// The assembled Express application, driven directly: Supertest binds it to an ephemeral port
// for the duration of each request, so these cases need no listener of their own. The integration
// suite is the one that exercises the exported HTTP server.
const app = require('../../app.js');

/**
 * Unit tests for the /hello endpoint
 *
 * Two contracts, and nothing else:
 *   - GET /hello answers 200 with the body exactly 'Hello world'
 *   - a path with no registered route answers 404, from Express's own default handler
 *
 * Method behaviour is not asserted here because the app registers no handler of its own for any
 * method other than the GET above: HEAD and OPTIONS on /hello are generated by Express for that
 * single GET registration, and POST, PUT, PATCH, DELETE and TRACE match nothing and fall through
 * to the same 404 as any unknown path.
 */
describe('/hello endpoint', () => {
    it('should return \'Hello world\' and a 200 status code', async () => {
        const response = await request(app)
            .get('/hello')
            .expect(200)
            .expect('Hello world');

        // The .expect() chain above already fails the test on a mismatch; these repeat the two
        // assertions on the resolved response so a failure names the value it saw.
        expect(response).toBeDefined();
        expect(response.text).toBe('Hello world');
        expect(response.status).toBe(200);
    });

    it('should return a 404 status code for non-existent routes', async () => {
        const response = await request(app)
            .get('/nonexistent')
            .expect(404);

        // Only the status is asserted: an unmatched request never reaches the error middleware,
        // so the body is Express's own default 404 page and its content is not this
        // application's contract.
        expect(response).toBeDefined();
        expect(response.status).toBe(404);
    });
});
