const express = require('express');

/**
 * Router for the /hello endpoint
 *
 * This router owns the only application route the tutorial publishes. It is never mounted
 * directly by app.js; the path is composed over two hops, which is why the registration below
 * is '/' rather than '/hello':
 *
 *     '/' (app.js)  +  '/hello' (routes/index.js)  +  '/' (here)  =  GET /hello
 */
const router = express.Router();

/**
 * The single registered handler: GET on this router's root, reached as GET /hello.
 *
 * Response contract, relied on by both Jest suites, the container health check, the Kubernetes
 * probes and the tutorial documentation:
 *   - status 200, set by Express because res.send() completed without an error
 *   - Content-Type: text/html; charset=utf-8 - what res.send() chooses for a string argument
 *   - body exactly `Hello world`, 11 bytes, with no trailing newline
 *
 * Method behaviour follows from this being the only registration:
 *   - HEAD /hello answers 200 with headers only, and OPTIONS /hello answers 200 with
 *     `Allow: GET, HEAD`. Both are generated by Express for this GET route, not extra routes
 *   - POST, PUT, PATCH, DELETE and TRACE on /hello match no handler and fall through to
 *     Express's own 404. There is no method gate here and no 405 response anywhere
 *
 * @param {express.Request} req - Express request object
 * @param {express.Response} res - Express response object
 * @returns {void} Ends the request-response cycle
 */
router.get('/', (req, res) => {
    res.send('Hello world');
});

module.exports = router;
